version: '2'
services:
  blog:
      build: .
      volumes:
        - .:/blog
        - /var/www/log:/log
  nginx:
    image: daocloud.io/nginx:stable-alpine
    depends_on:
      - blog
    volumes:
      - ./blog_nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/blog
      - /var/www/log:/log
    ports:
      - "80:8080"
